### ISSUE TITLE
Doesn't work | Window doesn't show up

### ISSUE THREAD

**Issue by W1nOfGood** [SEOL-creator/ae-plugin-apple-music-styled-lyrics-generator#1]
I have watched both the guide video and followed correctly when I go to Window ---> Extension ---> APMS Lyrics it doesn't show up (the make window).

**Comment by SEOL-creator** [comment]
Sorry for the confusion. 

APMSL is not being distributed signed, so you need to enable debugging of unsigned extensions to run it.
This was not written in the readme.   

#

[Quoted from adobe cep cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions)

### Debugging Unsigned Extensions

If you are in the midst of development and want to bypass the need to sign your extensions, you can bypass the check for extension signatures by editing the CSXS preference properties file, located at:

 - Win: regedit > HKEY_CURRENT_USER/Software/Adobe/CSXS.11, then add a new entry PlayerDebugMode of type "string" with the value of "1".
 - macOS: In the terminal, type: `defaults write com.adobe.CSXS.11 PlayerDebugMode 1` (The plist is also located at /Users/`<username>`/Library/Preferences/com.adobe.CSXS.11.plist)


### Special notes for macOS

Staring with macOS 10.9, Apple introduced a caching mechanism for plist files. Your modifications to plist files does not take effect until the cache gets updated (on a periodic basis, you cannot know exactly when the update will happen). To make sure your modifications take effect, there are two methods.

 - Kill **cfprefsd** process. It will restart automatically. Then the update
   takes effect.
 - Restart your macOS, or log out the current user and re-log in.
 - [More Information](http://hints.macworld.com/article.php?story=20130908042828630)

**Comment by W1nOfGood** [comment]
Thank you! This has fixed the issue.
